  extends:
    - eslint:recommended
  plugins:
    - react
  rules:
    no-useless-escape: 0
    prefer-const: warn
    no-unused-vars: warn
    no-undef: warn
    no-lone-blocks: warn
    react/prop-types: 0
    react/no-string-refs: 0
    react/no-find-dom-node: warn
    react/no-render-return-value: warn
    react/no-deprecated: warn